version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: introducaodockerdb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_DB}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: docek-api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTAINER}
      JWT_SECRET: ${JWT_SECRET}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
