
export const courses = [
  {
    name: "Introdução à Programação com JavaScript",
    description: "Aprenda os fundamentos da programação usando JavaScript.",
    workload: 40,
    price: 199,
  },
  {
    name: "HTML e CSS para Iniciantes",
    description: "Curso completo de marcação e estilização de páginas web.",
    workload: 35,
    price: 149,
  },
  {
    name: "Desenvolvimento Web com React",
    description: "Aprenda a criar aplicações modernas usando React.",
    workload: 60,
    price: 299,
  },
  {
    name: "Node.js e Express.js",
    description: "Construa APIs escaláveis com Node.js e Express.",
    workload: 50,
    price: 259,
  },
  {
    name: "Banco de Dados com MySQL",
    description: "Curso de modelagem e queries com MySQL.",
    workload: 45,
    price: 199,
  },
  {
    name: "Python para Ciência de Dados",
    description: "Explore bibliotecas e técnicas para análise de dados.",
    workload: 80,
    price: 399,
  },
  {
    name: "Machine Learning com Python",
    description: "Aprenda a criar modelos de aprendizado de máquina.",
    workload: 90,
    price: 499,
  },
  {
    name: "Introdução ao TypeScript",
    description: "Curso básico de tipagem estática em JavaScript.",
    workload: 30,
    price: 179,
  },
  {
    name: "Programação Orientada a Objetos em Java",
    description: "Fundamentos e práticas da POO com Java.",
    workload: 55,
    price: 249,
  },
  {
    name: "Spring Boot para Iniciantes",
    description: "Crie aplicações web robustas com Spring Boot.",
    workload: 70,
    price: 349,
  },
  {
    name: "C# e .NET Core",
    description: "Aprenda a programar com C# e desenvolver APIs no .NET Core.",
    workload: 65,
    price: 299,
  },
  {
    name: "Fundamentos de Segurança da Informação",
    description: "Entenda os principais conceitos de cibersegurança.",
    workload: 40,
    price: 229,
  },
  {
    name: "Linux para Desenvolvedores",
    description: "Comandos essenciais e administração de sistemas Linux.",
    workload: 35,
    price: 189,
  },
  {
    name: "Docker e Kubernetes",
    description: "Aprenda a criar e orquestrar containers.",
    workload: 75,
    price: 399,
  },
  {
    name: "Git e GitHub",
    description: "Controle de versão e colaboração em projetos.",
    workload: 25,
    price: 129,
  },
  {
    name: "DevOps com CI/CD",
    description: "Automatize deploys e pipelines com ferramentas modernas.",
    workload: 60,
    price: 349,
  },
  {
    name: "UI/UX Design",
    description: "Princípios de design de interfaces e experiência do usuário.",
    workload: 50,
    price: 279,
  },
  {
    name: "Design Gráfico com Photoshop",
    description: "Criação e edição de imagens profissionais.",
    workload: 45,
    price: 199,
  },
  {
    name: "Excel Avançado",
    description: "Funções, dashboards e automações no Excel.",
    workload: 30,
    price: 159,
  },
  {
    name: "Power BI para Análise de Dados",
    description: "Visualize e analise dados com dashboards interativos.",
    workload: 40,
    price: 229,
  },
  {
    name: "Marketing Digital para Iniciantes",
    description: "Aprenda estratégias de marketing online.",
    workload: 35,
    price: 179,
  },
  {
    name: "SEO Avançado",
    description: "Otimize sites para melhores resultados no Google.",
    workload: 30,
    price: 199,
  },
  {
    name: "Copywriting e Escrita Persuasiva",
    description: "Técnicas para textos que vendem.",
    workload: 25,
    price: 149,
  },
  {
    name: "Fotografia Digital",
    description: "Aprenda técnicas de fotografia profissional.",
    workload: 45,
    price: 199,
  },
  {
    name: "Edição de Vídeos com Premiere",
    description: "Produção e edição de vídeos de qualidade.",
    workload: 50,
    price: 249,
  },
  {
    name: "Ilustração Digital com Illustrator",
    description: "Curso completo de criação vetorial.",
    workload: 40,
    price: 199,
  },
  {
    name: "Finanças Pessoais",
    description: "Controle seu dinheiro e aprenda a investir.",
    workload: 25,
    price: 139,
  },
  {
    name: "Investimentos em Ações",
    description: "Aprenda estratégias para investir em ações.",
    workload: 35,
    price: 229,
  },
  {
    name: "Criação de Startups",
    description: "Como planejar e executar um negócio digital.",
    workload: 50,
    price: 299,
  },
  {
    name: "Gestão de Projetos com Scrum",
    description: "Fundamentos de metodologias ágeis.",
    workload: 35,
    price: 179,
  },
  {
    name: "Inglês para Programadores",
    description: "Vocabulário e frases mais usadas em TI.",
    workload: 30,
    price: 159,
  },
  {
    name: "Espanhol Básico",
    description: "Aprenda o essencial do idioma espanhol.",
    workload: 40,
    price: 179,
  },
  {
    name: "Francês para Viagens",
    description: "Frases úteis para comunicação em francês.",
    workload: 25,
    price: 129,
  },
  {
    name: "Matemática Básica",
    description: "Reforce seus conhecimentos em matemática fundamental.",
    workload: 30,
    price: 99,
  },
  {
    name: "Estatística para Iniciantes",
    description: "Introdução à análise estatística.",
    workload: 35,
    price: 149,
  },
  {
    name: "Engenharia de Software",
    description: "Fundamentos de arquitetura e boas práticas de software.",
    workload: 60,
    price: 299,
  },
  {
    name: "Arquitetura de Microsserviços",
    description: "Planejamento e implementação de microsserviços.",
    workload: 70,
    price: 399,
  },
  {
    name: "Inteligência Artificial Aplicada",
    description: "Uso prático de IA em aplicações reais.",
    workload: 85,
    price: 499,
  },
  {
    name: "Blockchain e Criptomoedas",
    description: "Entenda como funciona o mundo cripto.",
    workload: 60,
    price: 349,
  },
  {
    name: "Realidade Virtual e Aumentada",
    description: "Criação de experiências imersivas.",
    workload: 75,
    price: 399,
  },
  {
    name: "Desenvolvimento de Games com Unity",
    description: "Curso completo de criação de jogos.",
    workload: 80,
    price: 449,
  },
  {
    name: "Arduino e Eletrônica Básica",
    description: "Projetos práticos com Arduino.",
    workload: 50,
    price: 249,
  },
  {
    name: "Robótica para Iniciantes",
    description: "Construa robôs simples do zero.",
    workload: 60,
    price: 299,
  },
  {
    name: "Automação com Python",
    description: "Crie scripts para automatizar tarefas.",
    workload: 40,
    price: 229,
  },
  {
    name: "Chatbots com IA",
    description: "Desenvolvimento de chatbots inteligentes.",
    workload: 55,
    price: 349,
  },
  {
    name: "Cybersecurity para Desenvolvedores",
    description: "Proteja suas aplicações contra ataques.",
    workload: 65,
    price: 379,
  },
  {
    name: "Criação de APIs REST",
    description: "Boas práticas e implementação de APIs REST.",
    workload: 50,
    price: 249,
  },
  {
    name: "GraphQL do Zero",
    description: "Entenda e implemente GraphQL em seus projetos.",
    workload: 40,
    price: 229,
  },
  {
    name: "Testes Automatizados com Jest",
    description: "Escreva testes eficientes para seu código.",
    workload: 35,
    price: 189,
  },
  {
    name: "Arquitetura Limpa em Node.js",
    description: "Organize projetos Node.js com boas práticas.",
    workload: 60,
    price: 329,
  },
];

